apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmb-redis
  namespace: bookmybox
  labels:
    app.kubernetes.io/name: bookmybox
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmb-redis
  template:
    metadata:
      labels:
        app: bmb-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bmb-redis-service
  namespace: bookmybox
  labels:
    app.kubernetes.io/name: bookmybox
    app.kubernetes.io/component: cache
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: bmb-redis
  type: ClusterIP
