/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddGroundRouteImport } from './routes/add-ground'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroundsIndexRouteImport } from './routes/grounds.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GroundsIdRouteImport } from './routes/grounds.$id'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BookingGroundIdRouteImport } from './routes/booking.$groundId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminGroundsRouteImport } from './routes/admin.grounds'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddGroundRoute = AddGroundRouteImport.update({
  id: '/add-ground',
  path: '/add-ground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundsIndexRoute = GroundsIndexRouteImport.update({
  id: '/grounds/',
  path: '/grounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GroundsIdRoute = GroundsIdRouteImport.update({
  id: '/grounds/$id',
  path: '/grounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const BookingGroundIdRoute = BookingGroundIdRouteImport.update({
  id: '/booking/$groundId',
  path: '/booking/$groundId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroundsRoute = AdminGroundsRouteImport.update({
  id: '/grounds',
  path: '/grounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-ground': typeof AddGroundRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$groundId': typeof BookingGroundIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/grounds/': typeof GroundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-ground': typeof AddGroundRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$groundId': typeof BookingGroundIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/grounds': typeof GroundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-ground': typeof AddGroundRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/grounds': typeof AdminGroundsRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$groundId': typeof BookingGroundIdRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/grounds/$id': typeof GroundsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/grounds/': typeof GroundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-ground'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/booking/$groundId'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/grounds/$id'
    | '/admin/'
    | '/dashboard/'
    | '/grounds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-ground'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/booking/$groundId'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/grounds/$id'
    | '/admin'
    | '/dashboard'
    | '/grounds'
  id:
    | '__root__'
    | '/'
    | '/add-ground'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/bookings'
    | '/admin/grounds'
    | '/admin/slots'
    | '/admin/users'
    | '/booking/$groundId'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/grounds/$id'
    | '/admin/'
    | '/dashboard/'
    | '/grounds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddGroundRoute: typeof AddGroundRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookingGroundIdRoute: typeof BookingGroundIdRoute
  GroundsIdRoute: typeof GroundsIdRoute
  GroundsIndexRoute: typeof GroundsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ground': {
      id: '/add-ground'
      path: '/add-ground'
      fullPath: '/add-ground'
      preLoaderRoute: typeof AddGroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grounds/': {
      id: '/grounds/'
      path: '/grounds'
      fullPath: '/grounds/'
      preLoaderRoute: typeof GroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/grounds/$id': {
      id: '/grounds/$id'
      path: '/grounds/$id'
      fullPath: '/grounds/$id'
      preLoaderRoute: typeof GroundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/booking/$groundId': {
      id: '/booking/$groundId'
      path: '/booking/$groundId'
      fullPath: '/booking/$groundId'
      preLoaderRoute: typeof BookingGroundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grounds': {
      id: '/admin/grounds'
      path: '/grounds'
      fullPath: '/admin/grounds'
      preLoaderRoute: typeof AdminGroundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminGroundsRoute: typeof AdminGroundsRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminGroundsRoute: AdminGroundsRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddGroundRoute: AddGroundRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookingGroundIdRoute: BookingGroundIdRoute,
  GroundsIdRoute: GroundsIdRoute,
  GroundsIndexRoute: GroundsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
